# fly.toml app configuration file generated for finalytics-server on 2023-08-03T19:17:02-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "finalytics-server"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
